spring:
  datasource:
    url: jdbc:h2:./bank_account;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9092
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never # Set to always for first run then to never or delete bank_account** files in root directory for consequent runs
